spring:
  rabbitmq:
    host: 192.168.195.129
    port: 5672
    username: admin
    password: admin
    virtual-host: /admin
    listener:
      simple:
        #消息的手动确认
        acknowledge-mode: manual